### ISSUE TITLE
Defunct Documentation

### ISSUE THREAD

**Issue by DavidROwen** [libtcod/libtcod#22]
The readme links to the roguecentral.org documentation but that site seems to be defunct (the link just times out), so there is just the incomplete current documentation available.

**Comment by HexDecimal** [comment]
It looks like [roguecentral.org](http://roguecentral.org/) is down completely.  That's too bad since there's still a lot that needs to be done for the new documentation.  A lot of the wait comes from my unfamiliarity with Doxygen which seems to give all-or-nothing output in some cases.

The old docs still exist compiled [in the repository itself](https://github.com/libtcod/libtcod/tree/1.5.1/doc), but you'd need to [download them](https://github.com/libtcod/libtcod/archive/1.5.1.zip) to view them.

**Comment by HexDecimal** [comment]
I was able to fix the issues with Doxygen.  What's left is just a lot of work adding docs for C functions and converting the C++ docs.

**Comment by HexDecimal** [comment]
It will still be a lot of work to make the new documentation up-to-date.

Until then the [old documentation is back online](https://libtcod.github.io/docs/).
