### ISSUE TITLE
Build without SDL

### ISSUE THREAD

**Issue by TinkerWorX** [libtcod/libtcod#25]
Is it possible to build this without the SDL requirements, to enable using the utility part of the library without having bundle SDL?

Attempting to load the library dynamically will fail if SDL isn't present, even if it is unused.

**Comment by MichaelMackus** [comment]
I noticed in the linked [BitBucket issue](https://bitbucket.org/libtcod/libtcod/issues/90/make-sure-libtcod-builds-without-sdl2-or) there were multiple references to relying on SDL2 types. Any clarification on what types we're relying on SDL2 for would be helpful, I looked in the mentioned `fov.h` file but didn't see any references to SDL2 specifically there. I'm sure the BitBucket issue is old, but perhaps it would be easier to implement this now if we don't rely on SDL2 for pathfinding, FOV, and other non-graphics related features.

**Comment by HexDecimal** [comment]
`fov.h` was an example of something already not dependent on SDL.  The problem modules were the image and console modules and the internal tileset all of which I've since cleaned up to no longer use SDL surfaces.

What's left are the mostly unavoidable modules: rendering contexts, event handling, and some timing functions.  To finish the work those could need to be wrapped in simple `NO_SDL` conditions.

But this issue hasn't been a my biggest priority.

**Comment by davemoore22** [comment]
Here's a possibly _very ambitious_ stretch goal for version 2/3 - allow libtcod to render to different render destinations such as a SFML window as well as SDL. I've currently got an SFML project on the go as well as a libtcod/SDL project and I miss libtcod on SFML!

**Comment by HexDecimal** [comment]
> allow libtcod to render to different render destinations such as a SFML window as well as SDL

Technically already supported by the current context system.  The main problem is how libraries link together in C more than the actual implementation of it.  The only reasonable way of doing this is to make a new library dependent on SFML which implements a new context for libtcod.

**Comment by HexDecimal** [comment]
Libtcod can now be built without SDL by passing the `-DLIBTCOD_SDL2=disable` flag to CMake.
