### ISSUE TITLE
Why TCODList instead of strandard stl containers?

### ISSUE THREAD

**Issue by JasonMarechal25** [libtcod/libtcod#32]
I'm curious as to why a custom list implementation has been chosen instead of using standard stl containers?

**Comment by HexDecimal** [comment]
I assume TCODList was from when libtcod was only C. When the C++ API was made TCODList got ported to C++ directly instead of using more appropriate `std::vector` templates.

I haven't quite gotten around to removing TCODList from the C++ API due to my inexperience at the time.  If you're using any functions where you'd prefer vectors then I can update them now.

**Comment by JasonMarechal25** [comment]
I'm following the tutorial on roguebasin and wanted to use shared_ptr instead of raw pointers but TCodlist clearAndDelete doesn't support shared_ptr.
I don't have any need, it was simple curiosity.
