### ISSUE TITLE
updateChar not working

### ISSUE THREAD

**Issue by kryptkicker** [libtcod/libtcod#38]
In MSVC++ 2017 using libtcod 1.14.0 coupled with the SDL2 renderer the following does not actually change anything, there are no errors produced:

`int base = 0x300;`
`TCODSystem::updateChar(base, 0, 16, mImgTest, 0, 0);`
`mConsole->mapAsciiCodeToFont(base, 0, 16);`
`mConsole->putChar(10, 0, base);`

I do load a custom font with blank spaces around the standard font, doubling the size of both dimensions. I should point out that this function only works on the SDL renderer, but then literally nothing else I have comes out correctly, no matter which renderer besides SDL2 that I use i.e. regular text, standard box drawing, etc. not to mention some crashes here and there.  

The custom test image DOES load and blits (regular and 2x modes) perfectly fine. It's currently one cell size of the font, which is 12x12.

I then tried updating to libtcod 1.15.1 but it still didn't work, and while the image would load and blit, blit2x produced markedly bad results.

**Comment by HexDecimal** [comment]
`TCODSystem::updateChar` assumes using the older renderers.  For now you should edit your font to include your characters instead of using `updateChar`, or stick with the older renderers only.

> I do load a custom font with blank spaces around the standard font, doubling the size of both dimensions.

Making the font wider will mess with the order of the glyphs.  It should only be made longer.  This will solve your problems with `frame` and `blit2x`.

In later versions of libtcod `frame` and `blit2x` are using Unicode characters for box drawing.  This breaks if you've made the font wider, but you still can set those Unicode codepoints manually.

It will take a long time for me to fix this properly.  So hopefully I've explained how to work around it well enough.

**Comment by kryptkicker** [comment]
Yes, excellent explanation, at least now I know what to do, thank you for the quick reply and advice I appreciate it! Awesome library all the way around!

**Comment by HexDecimal** [comment]
This should be fixed for all renderers in the recent alpha builds of libtcod, and in python-tcod.  Also keep in mind that you'll no longer need to resize the image to get more tiles, the virtual tileset you get to work with is infinitely tall.
