### ISSUE TITLE
Allow for a set window size, SDL_OPTIONS, etc 

### ISSUE THREAD

**Issue by l4tte** [libtcod/libtcod#76]
I'd be happy to take up this one if its a feature that should be implemented. The way the size of the screen works now is pretty poor. Instead of the size of each tiles being based on the image, you should be able to pass a size for the window and draw the tiles accordingly. Furthermore, things like keep aspect and SDL_Options could be easily set while being passed to TCODConsole initroot (Or a new function like TCODConsole::setOptions, etc etc).
I'd be happy to implement this if this is a good feature!

**Comment by HexDecimal** [comment]
This functionally already exists with `TCOD_context_new_window` (in `context_init.h`,) contexts also give you some options on how the console would be scaled to fit the space like the keep aspect option you mentioned.

Anything more complex than that would be handled by the new SDL2 renderer `renderer_sdl2.h`.

Neither of these options are stable or have C++ ports yet.  Right now you'd need to use C types to interact with them from C++.

**Comment by l4tte** [comment]
TCOD_context_new_window requires using the entire context API, which means pretty much handling the terminal yourself. There should probably be some optional args in `TCODConsole::initRoot` that would be passed into `TCOD_context_new_window`

**Comment by HexDecimal** [comment]
Handing the terminal yourself only means creating your own Console object and passing that to the Context's present function instead of using global singletons for both.

Because everything internally has already been switched to using contexts it should be possible to add parameters to `TCODConsole::initRoot`.  I'm trying to move users away from it since I no longer want to maintain these singletons.  Once a proper C++ API for contexts is in place `initRoot` will be deprecated.  My long term plans are to deprecate the `TCODConsole` namespace entirely.

Keeping that in mind I would accept a PR for additions to `TCODConsole::initRoot`. The hard part is there isn't a good setup to document changes to any of the old C++ API.  The old documentation generator is no longer used and the current C++ docstrings are mostly incompatible with Doxygen.

**Comment by l4tte** [comment]
Ohh, that makes sense. If you're already going to deprecate it then I'll probably just leave it, especially with the documentation problem. Thanks!
